export const ACTIVE_EVENT_LUCKY_MOON = "ACTIVE_EVENT_LUCKY_MOON";
export const GET_LANTERN_COLLECTION = "GET_LANTERN_COLLECTION";
export const SPIN_LUCKY_MOON = "SPIN_LUCKY_MOON";
export const GET_RANK_TABLE = "GET_RANK_TABLE"